model:
  class_path: otx.algo.diffusion.model.ldm.OTXLatentDiffusion
  init_args:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "images"
    cond_stage_key: "captions"
    image_size: 64
    channels: 4
    cond_stage_trainable: false   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False

    optimizer:
      class_path: torch.optim.AdamW
      init_args:
        lr: 1e-4
        betas: [0.9, 0.999]
        weight_decay: 1e-2
        eps: 1e-08

    scheduler:
      class_path: torch.optim.lr_scheduler.ConstantLR
      init_args:
        factor: 1.0

    unet_config:
      target: otx.algo.diffusion.model.ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: otx.algo.diffusion.model.ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: otx.algo.diffusion.model.ldm.modules.encoders.modules.FrozenCLIPEmbedder
precision: 16-mixed


logger:
  - class_path: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: ""
      name: "tensorboard/"
      log_graph: false
      default_hp_metric: true
      prefix: ""
engine:
  task: DIFFUSION
  device: auto

callback_monitor: val/loss_simple_ema

data: ../_base_/data/diffusion.yaml
max_epochs: 50
