model:
  class_path: otx.algo.diffusion.OTXStableDiffusion
  init_args:
    in_ch: 4
    out_ch: 4
    model_ch: 320
    attention_resolutions: [4, 2, 1]
    num_res_blocks: 2
    channel_mult: [1, 2, 4, 4]
    n_heads: 8
    transformer_depth: [1, 1, 1, 1]
    ctx_dim: 768
    use_linear: False
    checkpoint_url: https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt

    optimizer:
      class_path: torch.optim.AdamW
      init_args:
        lr: 1e-4
        betas: [0.9, 0.999]
        weight_decay: 1e-2
        eps: 1e-08

    scheduler:
      class_path: torch.optim.lr_scheduler.ConstantLR
      init_args:
        factor: 1.0

engine:
  task: DIFFUSION
  device: auto

callback_monitor: val/fid

data: ../_base_/data/diffusion.yaml
max_epochs: 50
